name: PersonalWeapon
version: '${project.version}'
main: net.wax0n.personalweapon.PersonalWeapon
api-version: '1.20'
commands:
  createweapon:
    usage: /createweapon name
    description: Create a personal weapon
  pweapon:
    usage: /pweapon <rename/texture/info/delete>
    description: Use this for all :3
    aliases: pw